language: java
jdk:
  - openjdk17

# Travis CI 실행 브랜치 설정
branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main 브랜치에 push 됐을 때 수행할 명령어 설정
script: "./gradlew clean build"

# CI 완료 알림을 발송할 메일 주소 설정
notifications:
  email:
    recipients:
      - heextory@icloud.com

# 배포 파일을 S3로 전달하도록 설정
before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/spring-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sample-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: main
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: sample-springboot-build
    key: sample-springboot-webservice.zip
    bundle_type: zip
    application: sample-springboot-webservice
    deployment_group: sample-springboot-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main
